### ISSUE TITLE
Getting error while trying to send diagnostic request

### ISSUE THREAD

**Issue by Melvin3096** [chaitu-ycr/py_canoe#4]
I'm trying to use py_canoe package to open CANoe and send diagnostic requests to the ECU. The package seems to open the CANoe cfg file but when i try to send the diagnostic request ('10 01'), I'm facing the below error.
**Traceback (most recent call last):
  File "D:\CS_Python_MSV\canoe.py", line 14, in <module>
    resp = canoe_inst.send_diag_request("Door", '10 01')
  File "C:\Users\VF_KPIT\AppData\Roaming\Python\Python39\site-packages\py_canoe.py", line 629, in send_diag_request
    diag_req.Send()
  File "<COMObject CreateRequestFromStream>", line 2, in Send
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147467259), None)**

I'm using Python 3.9.9 version and pywin32 is installed properly. 
![image](https://user-images.githubusercontent.com/89288351/226379242-93736482-1472-42c1-9f31-973c821f37e4.png)

Any solution on how to get this issue sorted would be appreciated. Thank you

**Comment by Melvin3096** [comment]
This issue occurred because the python packages in my PC were not properly installed. After a clean installation of all the internal python packages, everything seemed to work fine
